#!/bin/bash

build() {
    local mod

    add_module 'dm-crypt'
    add_module 'dm-integrity'
    if [[ -n $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules '/crypto/'
    fi

    add_binary 'cryptsetup'

    map add_udev_rule \
        '10-dm.rules' \
        '13-dm-disk.rules' \
        '95-dm-notify.rules' \
        '/usr/lib/initcpio/udev/11-dm-initramfs.rules'

    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
    add_binary '/usr/lib/libgcc_s.so.1'

    # cryptsetup loads the legacy provider which is required for whirlpool
    add_binary '/usr/lib/ossl-modules/legacy.so'

    add_module 'hid_multitouch'
    add_module 'hid_generic'

    add_binary 'unl0kr'
    add_file '/etc/unl0kr.conf'

    map add_udev_rule \
        '60-drm.rules' \
        '60-input-id.rules' \
        '60-persistent-input.rules' \
        '70-mouse.rules' \
        '70-touchpad.rules' \
        '80-libinput-device-groups.rules'

    add_full_dir '/usr/share/libinput'
    add_full_dir '/usr/share/X11/xkb'

    add_runscript
}

help() {
    cat <<HELPEOF
This hook is for unlocking LUKS partitions with unl0kr.
HELPEOF
}
