name: Markdownlint
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: ruzickap/action-my-markdown-linter@v1
